### ISSUE TITLE
Reduce registry load from GrscicollLookupServiceIndexerFromHiveTable

### ISSUE THREAD

**Issue by MattBlissett** [gbif/key-value-store#42]
The weekly job refreshing the index causes a high load on the registry for a long time.

Could we either:

- simply dump the cache, and let it refill naturally as pipelines needs it?
- or set the HBase TTL to an appropriate value (e.g. a week) so old entries expire automatically, without needing any scheduled job?

**Comment by marcos-lg** [comment]
Let's see how that works. If it doesn't help I can change the lookup code in the registry to run less queries. Right now it's a `UNION ALL` query but in some cases (for example, ther `verbose` param is false) we might be able to skip some subqueries.

**Comment by marcos-lg** [comment]
I have added another index and the wf takes now only 45 minutes (it used to be more than 8h) and the DB load is lower.
